server:
  port: 8087

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: sairam.paidipati32@gmail.com
    password: oplj qscp xdst nwmk
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#  twilio:
#    account-sid: sid
#    auth-token: token
#    phone-number:phone

  datasource:
    url: jdbc:mysql://localhost:3306/stayease_notification_db
    username: root
    password: 2000030757
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true




